solsys_code/solsys_code_observatory/urls.py
from django.urls import path

from solsys_code.solsys_code_observatory.views import CreateObservatory, ObservatoryDetailView, ObservatoryList

app_name = 'solsys_code.solsys_code_observatory'

urlpatterns = [
    # path('create/<str:mpccode>/', CreateObservatory.as_view(), name='create'),
    path('create/', CreateObservatory.as_view(), name='create'),
    path('<int:pk>/', ObservatoryDetailView.as_view(), name='detail'),
    path('', ObservatoryList.as_view(), name='list'),
]

src/fomo/urls.py
from django.urls import include, path

from solsys_code.views import Ephemeris, MakeEphemerisView

urlpatterns = [
    path('observatory/', include('solsys_code.solsys_code_observatory.urls', namespace='solsys_code_observatory')),
    path('ephem/<int:pk>/', Ephemeris.as_view(), name='ephem'),
    path('targets/<int:pk>/makeephem/', MakeEphemerisView.as_view(), name='makeephem'),
    path('', include('tom_common.urls')),
]

solsys_code/solsys_code_observatory/models.py
from math import atan2, cos, degrees, radians, sin

import erfa
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils import timezone


class Observatory(models.Model):
    """class/Model to hold and handle MPC observatories defined by their
    observatory code.
    Uses the Observatory Codes API (https://minorplanetcenter.net/mpcops/documentation/obscodes-api/)
    """

    OPTICAL_OBSTYPE = 0
    OCCULTATION_OBSTYPE = 1
    SATELLITE_OBSTYPE = 2
    RADAR_OBSTYPE = 4
    OBSTYPE_CHOICES = (
        (OPTICAL_OBSTYPE, 'Optical'),
        (OCCULTATION_OBSTYPE, 'Occultation'),
        (SATELLITE_OBSTYPE, 'Satellite'),
        (RADAR_OBSTYPE, 'Radar'),
    )
    obscode = models.CharField(
        max_length=4, null=False, blank=False, default=None, unique=True, verbose_name='MPC observatory code'
    )
    name = models.CharField(
        max_length=255, null=False, blank=False, default=None, unique=True, verbose_name='Name of the observatory'
    )
    short_name = models.CharField(max_length=255, verbose_name='Short version of observatory name')
    lon = models.FloatField(
        null=True,
        blank=False,
        verbose_name='Longitude (East is positive) [deg]',
        validators=[
            MinValueValidator(-180.0, message='longitude must be greater than -180.'),
            MaxValueValidator(180.0, message='longitude must be less than 180.'),
        ],
        db_index=True,
    )
    lat = models.FloatField(
        null=True,
        blank=False,
        verbose_name='Latitude (North is positive) [deg]',
        validators=[
            MinValueValidator(-90.0, message='latitude must be greater than -90.'),
            MaxValueValidator(90.0, message='latitude must be less than 90.'),
        ],
        db_index=True,
    )
    altitude = models.FloatField(null=True, blank=False, default=0.0, verbose_name='Altitude [m]')
    observations_type = models.SmallIntegerField(
        'Observations Type', null=False, blank=False, default=0, choices=OBSTYPE_CHOICES
    )
    uses_two_line_obs = models.BooleanField(
        default=False, verbose_name='Whether this observatory uses two-line observations e.g. satellite/radar'
    )
    old_names = models.TextField(blank=True, verbose_name='Any previous names used by the observatory')
    created = models.DateTimeField(null=True, blank=False, editable=False, default=timezone.now)
    modified = models.DateTimeField(null=True, blank=True, editable=True, default=timezone.now)

    # Get Earth's equatorial radius and flattening factor for WGS84
    # reference ellipsoid. `r` is in meters
    _r, _f = erfa.eform(1)

    def __str__(self) -> str:
        return f'{self.obscode}: {self.name}'

    def from_parallax_constants(self, elong: float, rho_cos_phi: float, rho_sin_phi: float):
        """Convert from MPC parallax constants rho_cos_phi, rho_sin_phi to
        latitude, altitude and store these
        """

        # print(f"elong={elong:.6f} rhocosphi={rho_cos_phi:.6f} rhosinphi={rho_sin_phi:.6f}")

        # Form X,Y,Z vector (geocenter->observatory) from longitude and parallax constants, scaled to meters
        xyz = [
            self._r * cos(radians(elong)) * rho_cos_phi,
            self._r * sin(radians(elong)) * rho_cos_phi,
            self._r * rho_sin_phi,
        ]
        # Transform geocentric to geodetic
        lon, lat, alt = erfa.gc2gde(self._r, self._f, xyz)
        self.lon = degrees(lon)
        self.lat = degrees(lat)
        self.altitude = alt

    @property
    def to_parallax_constants(self) -> tuple[float, float]:
        """Convert from latitude and altitude to MPC parallax constants rho_cos_phi, rho_sin_phi
        and return these
        """

        axis_ratio = 1.0 - self._f
        rho_cos_phi = rho_sin_phi = 0.0
        if self.lat and self.lon and self.altitude:
            u = atan2(sin(radians(self.lat)) * axis_ratio, cos(radians(self.lat)))
            rho_sin_phi = axis_ratio * sin(u) + (self.altitude / self._r) * sin(radians(self.lat))
            rho_cos_phi = cos(u) + (self.altitude / self._r) * cos(radians(self.lat))

        return rho_cos_phi, rho_sin_phi

    def to_geocentric(self) -> tuple[float, float, float]:  # Potentially support optional units later
        """Converts the observatory location to geocentric coordinates
        WGS84 ellipsoid is assumed and the values corresponding to that are
        set in the erfa.gd2gce() call

        Returns:
            tuple[float, float, float]: Geocentric position (x,y,z) in km
        """

        xyz = [None, None, None]
        if self.lat and self.lon and self.altitude:
            xyz = erfa.gd2gce(self._r, self._f, radians(self.lon), radians(self.lat), self.altitude)
            # Convert to km
            xyz /= 1000.0
        return xyz

    def to_geodetic(self) -> tuple[float, float, float]:
        """Returns the observatory location in geodetic coordinates
        (longitude, latitude, altitude/height). The longitude and latitude
        values are returned in radians, with East longitude positive and the
        altitude is returned in meters

        Returns
            tuple[float, float, float]: Geodetic position (lon,lat,height) in radians/m
        """
        return (radians(self.lon), radians(self.lat), self.altitude)

    def ObservatoryXYZ(self) -> tuple[float, float, float]:
        """Converts the observatory location to geocentric coordinates (in units of Earth radii)
        Provides similar functionality to Sorcha's Observatory.ObservatoryXYZ()

        Returns:
            tuple[float, float, float]: Geocentric position (x,y,z) in Earth radii
        """

        xyz = self.to_geocentric()
        if all(xyz):
            # Convert to Earth radii
            r_in_km = self._r / 1000.0
            xyz /= r_in_km
        return xyz

    @property
    def get_observations_type(self) -> str:
        """Returns the str version of the stored observations type"""
        obstype_choices = dict(self.OBSTYPE_CHOICES)
        return obstype_choices[self.observations_type]

    class Meta:  # noqa: D106
        verbose_name_plural = 'Observatories'

solsys_code/solsys_code_observatory/forms.py
from django import forms

from solsys_code.solsys_code_observatory.models import Observatory


class CreateObservatoryForm(forms.ModelForm):
    """
    Form for creating observatories by specifying the MPC code
    """

    obscode = forms.CharField(max_length=3, min_length=3)

    class Meta:  # noqa: D106
        model = Observatory
        fields = [
            'obscode',
        ]

    def clean_obscode(self):
        """Light cleaning of passed obscode to ensure it's uppercase as needed by the MPC"""
        cleaned_data = self.clean()
        obscode = cleaned_data.get('obscode', '')
        if obscode is not None:
            obscode = obscode.upper()
        return obscode

solsys_code/solsys_code_observatory/views.py
from typing import Any

from django.contrib import messages
from django.db.utils import IntegrityError
from django.forms import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView
from tom_catalogs.harvester import MissingDataException

from solsys_code.solsys_code_observatory.forms import CreateObservatoryForm
from solsys_code.solsys_code_observatory.models import Observatory
from solsys_code.solsys_code_observatory.utils import MPCObscodeFetcher


class CreateObservatory(CreateView):
    """Creates an Observatory object by retrieving the MPC code from the form
    and querying the MPC Obscodes API
    (https://www.minorplanetcenter.net/mpcops/documentation/obscodes-api/)"""

    model = Observatory
    form_class = CreateObservatoryForm
    template_name = 'solsys_code_observatory/observatory_create.html'

    def get_success_url(self):
        """Create a custom success_url to redirect to the detail page for the
        newly created Observatory.
        """
        return reverse_lazy('solsys_code_observatory:detail', kwargs={'pk': self.kwargs['pk']})

    def get_context_data(self, **kwargs):  # noqa: D102
        context = super().get_context_data(**kwargs)
        return context

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        """
        Runs after the form validation (which ensures that the obscode is uppercased (required))
        Performs the query through the MPC API using ``MPCObscodeFetcher()`` and then tries to
        create the ``Observatory`` through ``MPCObscodeFetcher.to_observatory(). This means
        we shouldn't/don't call the superclass's ``form_valid`` method as this will
        attempt to create a duplicate (which raises an IntegrityError)
        """
        obs = MPCObscodeFetcher()
        errors = obs.query(form.cleaned_data['obscode'])
        try:
            obs = obs.to_observatory()
            self.object = obs
            self.kwargs['pk'] = obs.pk
        except MissingDataException:
            if errors:
                form.add_error('obscode', errors.get('message', 'Invalid MPC site code'))
            return self.form_invalid(form)

        except IntegrityError:
            print('Attempt to create duplicate Observatory')
            messages.error(self.request, 'Attempt to create duplicate Observatory')

        return redirect(self.get_success_url())


class ObservatoryDetailView(DetailView):
    """Detailed view of one specific Observatory"""

    model = Observatory
    template_name = 'solsys_code_observatory/observatory_detail.html'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:  # noqa: D102
        return super().get_context_data(**kwargs)


class ObservatoryList(ListView):
    """Overview of all Observatory sites with basic parameters and link to details"""

    model = Observatory
    template_name = 'solsys_code_observatory/observatory_list.html'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:  # noqa: D102
        context = super().get_context_data(**kwargs)

        context['num_obs'] = Observatory.objects.count()
        context['observatory_list'] = Observatory.objects.all()

        return context

src/templates/solsys_code_observatory/observatory_create.html
{% extends 'tom_common/base.html' %}
{% load bootstrap4 %}
{% block title %}Create Observatory from MPC Code{% endblock %}

{% block content %}
<h4>Create a new Observatory in FOMO from MPC code. </h4>
<br>
<p>
  Please fill the form below.
  Your entry will then be retrieved with the MPC and the details returned.
  <br>
  (<a href=https://minorplanetcenter.net/iau/lists/ObsCodesF.html>This page</a> lists all the MPC site codes)
</p>
<form action="{% url 'solsys_code_observatory:create' %}" enctype="multipart/form-data" method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}

  {% buttons %}
  <button type="submit" class="btn btn-primary">
    {% if object %}
      Update
    {% else %}
      Create Observatory
    {% endif %}
  </button>
  {% endbuttons %}

</form>
{% endblock %}

src/templates/solsys_code_observatory/observatory_detail.html
{% extends 'tom_common/base.html' %}
{% load bootstrap4 %}
{% block title %}Observatory{% endblock %}

{% block content %}

<h1>Observatory: {{ observatory.name }} ({{observatory.obscode}})</h1>

<div class="row obs-details-container">
    <div class="col-md-12">
        <h2>Observatory details</h2>
        <table class="table">
            <thead>
                <tr>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        Longitude
                    </td>
                    <td>
                        {{ observatory.lon }} deg (East is positive)
                    </td>
                </tr>
                <tr>
                    <td>
                        Latitude
                    </td>
                    <td>
                        {{ observatory.lat }} deg (North is positive)
                    </td>
                </tr>
                <tr>
                    <td>
                        Altitude
                    </td>
                    <td>
                        {{ observatory.altitude }} m
                    </td>
                </tr>
                <tr>
                    <td>
                        Observation type
                    </td>
                    <td>
                        {{ observatory.get_observations_type }}
                    </td>
                </tr>                <tr>
                    <td>
                        Uses two line obs?
                    </td>
                    <td>
                        {{ observatory.uses_two_line_obs }}
                    </td>
                </tr>
                <tr>
                    <td>
                        Approx. limit magnitude
                    </td>
                    <td>
                        {{ observatory.approx_lim_mag }} mag
                    </td>
                </tr>
                <tr>
                    <td>
                        Filters
                    </td>
                    <td>
                        {{ observatory.filters }}
                    </td>
                </tr>
                <tr style="width: 50px;">
                    <td>
                        Previous names
                    </td>
                    <td><div class="multiline-text">
                        {{ observatory.old_names }}
                    </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

src/templates/solsys_code_observatory/observatory_list.html
{% extends 'tom_common/base.html' %}
{% load bootstrap4 %}
{% block title %}Observatory{% endblock %}

{% block content %}

<h1>Observatories in FOMO: {{ num_obs }} </h1>

<h4>List of observatories:</h4>

<div class="row">
  <div class="col-md-10">
          <table id="observatories-table" class="table table-hover sortable">
          <thead>
            <tr>
              <th>MPC Code</th><th>Observatory Name</th><th>Longitude</th><th>Latitude</th><th>Altitude</th>
              <th>Details</th>
            </tr>
          </thead>
          <tbody>
            {% for observatory in observatory_list %}
            <tr>
              <td>{{ observatory.obscode }}</td>
              <td>{{ observatory.name }}</td>
              <td>{{ observatory.lon|floatformat:6 }}</td>
              <td>{{ observatory.lat|floatformat:6 }}</td>
              <td>{{ observatory.altitude|floatformat:3 }}</td>
              <td>
                <a href="{% url 'solsys_code_observatory:detail' pk=observatory.id %}" title="Observatory details" class="btn  btn-primary">Details</a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
  </div>
</div>

<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.js"></script>
<script>
  $(document).ready(function() {
      $('#observatories-table').DataTable({
          "paging": false,
          "searching": false
      });
      $('#user-observatories-table').DataTable({
        "paging": false,
        "searching": false
    });
  });
  </script>

{% endblock %}